version: '3.8'

services:
  app:
    build: .
    ports:
      - "8003:8003"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/telegive_db
      - REDIS_URL=redis://redis:6379/0
      - TELEGIVE_AUTH_URL=http://auth-service:8001
      - TELEGIVE_CHANNEL_URL=http://channel-service:8002
      - TELEGIVE_PARTICIPANT_URL=http://participant-service:8004
      - TELEGIVE_BOT_URL=http://bot-service:8005
      - TELEGIVE_MEDIA_URL=http://media-service:8006
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=telegive_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

